### ISSUE TITLE
gettting reports not working

### ISSUE THREAD

**Issue by EchoStretch** [stooged/PS5-Server#2]
after the gzip fix i guess it hasnt been working. ps5 isnt going to the index.html
![error ps5](https://github.com/stooged/PS5-Server/assets/98502641/00bbe992-a347-4d42-9e22-474b61128393)

**Comment by EchoStretch** [comment]
seems it doesn't auto go to 10.1.1.1/index.html but when connect on your phone or computer and type 10.1.1.1 it will go

**Comment by stooged** [comment]
from what i can tell it is running into a memory error when all of the internal pages are addressed and ssl is used.

i commented out all of the internal pages and it works
https://github.com/stooged/PS5-Server/blob/main/PS5_Server/PS5_Server.ino#L887

i think this might have been why i only added a very simple version for the 8266 boards, for the ps5 i think its best to move up to the esp32 boards.

i also forgot to add the line to process the secure webserver in the loop
https://github.com/stooged/PS5-Server/blob/main/PS5_Server/PS5_Server.ino#L924

**Comment by EchoStretch** [comment]
Works great thanks alot
